# Generated by Django 2.0 on 2017-12-24 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('Helm', 'Helmet'), ('Chest', 'Chest'), ('Arms', 'Arms'), ('Waist', 'Waist'), ('Legs', 'Legs'), ('Charms', 'Charms'), ('Decorations', 'Decorations'), ('Palicoes', 'Palicoes')], max_length=11)),
                ('rarity', models.IntegerField(default=1)),
                ('defense', models.IntegerField()),
                ('decorations', models.IntegerField(default=0)),
                ('fire', models.IntegerField(default=0)),
                ('water', models.IntegerField(default=0)),
                ('lightning', models.IntegerField(default=0)),
                ('ice', models.IntegerField(default=0)),
                ('dragon', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
                ('category', models.CharField(choices=[('Mats', 'Materials'), ('Loot', 'Loot'), ('Other', 'Other')], max_length=5)),
                ('drop_chance', models.IntegerField()),
                ('gather_quant', models.IntegerField(default=1)),
                ('carve_spot', models.CharField(max_length=24)),
                ('description', models.TextField(max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='Mantle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('effects', models.TextField(max_length=256)),
                ('duration', models.IntegerField()),
                ('recharge', models.IntegerField()),
                ('description', models.TextField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('elements', models.IntegerField()),
                ('weakness', models.IntegerField()),
                ('resistances', models.IntegerField()),
                ('description', models.TextField(max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('GS', 'Greatsword'), ('SnS', 'Sword & Shield'), ('DB', 'Dual Blades'), ('LS', 'Longsword'), ('Hammer', 'Hammer'), ('HH', 'Hunting Horn'), ('Lance', 'Lance'), ('GL', 'Gunlance'), ('SA', 'Switch Axe'), ('CB', 'Charge Blade'), ('IG', 'Insect Glaive'), ('Bow', 'Bow'), ('LBG', 'Light Bowgun'), ('HBG', 'Heavy Bowgun')], max_length=6)),
                ('rarity', models.IntegerField(default=1)),
                ('attack_power', models.IntegerField()),
                ('sharpness', models.IntegerField(default=1)),
                ('affinity', models.IntegerField(default=0)),
                ('element', models.IntegerField(default=0)),
                ('decorations', models.IntegerField(default=0)),
                ('defense', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=2048)),
            ],
        ),
        migrations.AddField(
            model_name='monster',
            name='zones',
            field=models.ManyToManyField(to='entries.Zone'),
        ),
        migrations.AddField(
            model_name='item',
            name='drop_from',
            field=models.ManyToManyField(to='entries.Monster'),
        ),
        migrations.AddField(
            model_name='item',
            name='mats_req',
            field=models.ManyToManyField(blank=True, related_name='_item_mats_req_+', to='entries.Item'),
        ),
        migrations.AddField(
            model_name='item',
            name='zones',
            field=models.ManyToManyField(to='entries.Zone'),
        ),
    ]
