# Generated by Django 2.0 on 2017-12-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='buy_value',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='item',
            name='sell_value',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='item',
            name='stack_size',
            field=models.IntegerField(default=1),
        ),
    ]
