# Generated by Django 2.0 on 2017-12-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_auto_20171224_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='armor',
            name='description',
            field=models.TextField(default='', max_length=2048),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weapon',
            name='description',
            field=models.TextField(default='Meme', max_length=2048),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='carve_spot',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Mats', 'Crafting'), ('Carve', 'Carving'), ('Weap', 'Weapon'), ('Armor', 'Armor'), ('Other', 'Other')], max_length=5),
        ),
        migrations.AlterField(
            model_name='item',
            name='drop_from',
            field=models.ManyToManyField(blank=True, to='entries.Monster'),
        ),
    ]
