# Generated by Django 2.0 on 2017-12-25 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0004_zone_num_camps'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('AB', 'Attack Boost'), ('AD', 'Adrenaline'), ('AE', 'Aquatic Expert'), ('AS', 'Affinity Sliding'), ('Art', 'Artillery'), ('BBQ', 'BBQ Master'), ('BO', 'Botanist'), ('CH', 'Cliffhanger'), ('Con', 'Constitution'), ('DA', 'Dragon Attack'), ('DB', 'Defense Boost'), ('EE', 'Evade Extender'), ('Ent', 'Entomologist'), ('EW', 'Evade Window'), ('FA', 'Fire Attack'), ('Foc', 'Focus'), ('For', 'Fortify'), ('FR', 'Fire Resistance'), ('Grd', 'Guard'), ('HB', 'Health Boost'), ('HH', 'Honey Hunter'), ('HM', 'Horn Maestro'), ('HR', 'Hunger Resistance'), ('IA', 'Ice Attack'), ('Int', 'Intimidator'), ('IP', 'Item Prolonger'), ('IR', 'Ice Resistance'), ('JM', 'Jump Master'), ('MG', 'Master Gatherer'), ('MM', 'Master Mounter'), ('MR', 'Muck Resistance'), ('MaR', 'Marathon Runner'), ('Pal', 'Palico Rally'), ('PR', 'Paralysis Resistance'), ('PoR', 'Poison Resistance'), ('PT', 'Pro Transporter'), ('QS', 'Quick Shealth'), ('RS', 'Recovery Speed'), ('RU', 'Recovery Up'), ('SAB', 'Special Ammo Boost'), ('Sce', 'Scenthound'), ('SC', 'Slinger Capacity'), ('SpC', 'Speed Crawler'), ('SE', 'Speed Eating'), ('SpE', 'Sporepuff Expert'), ('Sl', 'Slugger'), ('SR', 'Stun Resistance'), ('SRU', 'Scoutfly Range Up'), ('SS', 'Stamina SurgeAttack Boost'), ('SpS', 'Speed Sharpening'), ('ST', 'Stamina Thief'), ('Stl', 'Stealth'), ('TA', 'Thunder Attack'), ('TR', 'Thunder Resistance'), ('WA', 'Water Attack'), ('Wi', 'Windproof'), ('WR', 'Water Resistance')], max_length=3)),
                ('description', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('B', 'Basic'), ('SB', 'Set Bonus'), ('Tog', 'Toggle')], max_length=3)),
                ('max_rank', models.IntegerField(default=7)),
                ('growth', models.TextField(max_length=1024)),
                ('affixed_to', models.ManyToManyField(to='entries.Armor')),
            ],
        ),
    ]
