# Generated by Django 2.0 on 2017-12-30 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0005_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name='item',
            name='drop_chance',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='zones',
            field=models.ManyToManyField(blank=True, to='entries.Zone'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='affixed_to',
            field=models.ManyToManyField(blank=True, to='entries.Armor'),
        ),
    ]
