# Generated by Django 2.0 on 2017-12-31 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0006_auto_20171230_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='rarity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='drop_chance',
            field=models.IntegerField(default=100),
        ),
    ]
