# Generated by Django 2.0 on 2017-12-31 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0008_auto_20171231_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='mats_req',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entries.Item'),
        ),
    ]
