# Generated by Django 2.0 on 2017-12-31 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0009_auto_20171231_0457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='mats_req',
        ),
        migrations.AddField(
            model_name='item',
            name='mats_req',
            field=models.ManyToManyField(blank=True, related_name='_item_mats_req_+', to='entries.Item'),
        ),
    ]
